Fix pathspec error in the Travis CI build environment
Travis CI makes a non-standard clone that does not include all refs, so
we must ensure we can switch to the *gh-pages* branch and prevent this
message:

> error: pathspec 'gh-pages' did not match any file(s) known to git.